var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/portal/page.js")
R.c("server/chunks/ssr/_2b55d38d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5d5aaa26._.js")
R.c("server/chunks/ssr/_81051dd7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3ba03da5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8ecbddb6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_e490d391._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_portal_page_actions_245a7fa2.js")
R.m(5125)
module.exports=R.m(5125).exports
